Update actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -10,6 +10,14 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
     steps:
+      - name: Check SSH key secret
+          run:|
+            if [ -z "${{ secrets.SSH_KEY }}" ]; then
+              echo "SSH_KEY secret is missing!"
+              exit 1
+            else
+              echo "SSH_KEY secret is set."
+            fi
       - name: Deploy via SSH
         uses: appleboy/ssh-action@v0.1.7
         with:
